### ISSUE TITLE
Update de.flapdoodle.embed.process to 2.0.3

### ISSUE THREAD

**Issue by saiya** [yandex-qatools/postgresql-embedded#132]
To improve JDK 10 compatibility, please update `de.flapdoodle.embed.process` to `2.0.3`.

Under 2.0.2, following stacktrace fills console:

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2370)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
	at ru.yandex.qatools.embed.postgresql.AbstractPGProcess.<init>(AbstractPGProcess.java:19)
```

See flapdoodle-oss/de.flapdoodle.embed.process#78 for details.

**Comment by ekoutanov** [comment]
Same here on version 2.9 on macos

**Comment by ekoutanov** [comment]
and consider replacing the `e.printStackTrace()` calls that are sprinkled throughout the code base with proper logging

**Comment by gofabian** [comment]
I am interested in getting to work embedded postgres with java 10. I am not sure whether this error actually is a problem. The database process is started anyway.

What has to be done to update embed.process to 2.0.3? Maybe I can contribute.. But I would like to know the current state.

Why does the existing pull request revert the version back to 2.0.2 in the second commit? https://github.com/yandex-qatools/postgresql-embedded/pull/133

**Comment by heruan** [comment]
Same here, JDK 10.0.2 getting the exception.

**Comment by sazzer** [comment]
I'm still getting the error on Java 11, though it doesn't seem to actually break anything. That's both on Linux (CircleCI) and on macOS.

**Comment by pablomusumeci** [comment]
Same here for JDK11
