### ISSUE TITLE
Failed to read PID file

### ISSUE THREAD

**Issue by normenmueller** [yandex-qatools/postgresql-embedded#135]
Running on macOS with the [Postgres App](https://postgresapp.com/), I always get the following error:

```
[error] r.y.q.e.p.PostgresProcess - Failed to read PID file (File '/var/folders/lh/rdl1gz9n1w3c60p9wqy1_4j40000gn/T/postgresql-embed-8b80eefd-4d77-4930-a2b4-02c05b20a921/db-content-c13d1e62-18d6-4151-a4c7-bc8523561fca/postmaster.pid' does not exist)
java.io.FileNotFoundException: File '/var/folders/lh/rdl1gz9n1w3c60p9wqy1_4j40000gn/T/postgresql-embed-8b80eefd-4d77-4930-a2b4-02c05b20a921/db-content-c13d1e62-18d6-4151-a4c7-bc8523561fca/postmaster.pid' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1783)
	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1819)
	at ru.yandex.qatools.embed.postgresql.PostgresProcess.onAfterProcessStart(PostgresProcess.java:255)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116)
	at ru.yandex.qatools.embed.postgresql.AbstractPGProcess.<init>(AbstractPGProcess.java:19)
	at ru.yandex.qatools.embed.postgresql.PostgresProcess.<init>(PostgresProcess.java:68)
	at ru.yandex.qatools.embed.postgresql.PostgresExecutable.start(PostgresExecutable.java:25)
	at ru.yandex.qatools.embed.postgresql.PostgresExecutable.start(PostgresExecutable.java:13)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
```

Any ideas how to fix this one?

**Comment by Reeebuuk** [comment]
I'm habing the same error. Using OSX 10.13.4.

**Comment by tocology** [comment]
Actually, I don't know the exact way to fix this issue, but I had the same error.
I'm using this 'postgresql-embedded' to test my codes and the codes are working good even though the issue is occurring.

Anyway, I removed the all the 'postgresql-embed-**' folders like '/var/folders/lh/rdl1gz9n1w3c60p9wqy1_4j40000gn/T/postgresql-embed-8b80eefd-4d77-4930-a2b4-02c05b20a921' of your case. I think the .pid file does not exist, however, the source code of the library is trying to find that. After then, the error disappeared.

I think a more exact way to fix that issue.

**Comment by brainoutsource** [comment]
Same here, OS X 10.13.6

**Comment by alinbrici** [comment]
I've seen this issue when I had an external postgres running and the port was already taken.

**Comment by hannahsquier** [comment]
I am getting the same issue without external postgres running. The issue started when my computer restarted unexpectedly in the middle of running a test. I assume that the process was not shut down correctly, but I have not been able to fix it even after clearing caches.

**Comment by ThomasStubbe** [comment]
I'm having the same issue

**Comment by tomgross** [comment]
There might be a leftover from another test. Try `sudo lsof -PiTCP -sTCP:LISTEN | grep "postgres"` on Mac.
