### ISSUE TITLE
FATAL:  ShmemIndex entry size is wrong for data structure "XLOG Ctl"

### ISSUE THREAD

**Issue by kasheylm** [yandex-qatools/postgresql-embedded#7]
Trying to run it on Win8 x64 and it fails (
At first there was installed another instanse of PostgreSql - after deleting the same error:

```
FATAL:  ShmemIndex entry size is wrong for data structure "XLOG Ctl": expected 273304, actual 4209304
```

Full log : 
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/denis.veselovsky/.m2/repository/org/slf4j/slf4j-log4j12/1.7.2/slf4j-log4j12-1.7.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/denis.veselovsky/.m2/repository/org/slf4j/slf4j-simple/1.7.7/slf4j-simple-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Extract C:\Users\denis.veselovsky\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
Extract C:\Users\denis.veselovsky\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
log4j:WARN No appenders could be found for logger (de.flapdoodle.embed.process.runtime.ProcessControl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[postgres error]LOG:  database system was shut down at 2015-06-08 13:23:21 EEST
[postgres error] LOG:  database system is ready to accept connections
[postgres error] LOG:  autovacuum launcher started
[postgres error] Jun 08, 2015 1:23:23 PM ru.yandex.qatools.embed.postgresql.PostgresProcess onAfterProcessStart
SEVERE: Failed to read PID file (File 'C:\Users\DENISV~1.ROK\AppData\Local\Temp\embedpostgres-db-e02fdf75-af19-4ac6-950f-bc5637cf0770\postmaster.pid' does not exist)
Extract C:\Users\denis.veselovsky\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START
FATAL:  ShmemIndex entry size is wrong for data structure "XLOG Ctl": expected 273304, actual 4209304
[postgres error] FATAL:  ShmemIndex entry size is wrong for data structure "XLOG Ctl": expected 273304, actual 4209304
[postgres error] FATAL:  ShmemIndex entry size is wrong for data structure "XLOG Ctl": expected 273304, actual 4209304
[postgres error] 
org.postgresql.util.PSQLException: FATAL: ShmemIndex entry size is wrong for data structure "XLOG Ctl": expected 273304, actual 4209304
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:420)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:195)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:41)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at ProxyTest.PostgreSqlTest.test1(PostgreSqlTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Jun 08, 2015 1:23:23 PM ru.yandex.qatools.embed.postgresql.PostgresProcess stopInternal
INFO: trying to stop postgresql
Extract C:\Users\denis.veselovsky\.embedpostgresql\postgresql-9.4.1-1-windows-x64-binaries.zip START

LOG:  could not open temporary statistics file "pg_stat/lobal.tmp": No such file or directory
[postgres error] Exception in thread "Thread-6" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at de.flapdoodle.embed.process.io.file.FileCleaner.forceDeleteOnExit(FileCleaner.java:52)
	at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:122)
	at ru.yandex.qatools.embed.postgresql.PostgresProcess.deleteTempFiles(PostgresProcess.java:143)
	at ru.yandex.qatools.embed.postgresql.PostgresProcess.stopInternal(PostgresProcess.java:74)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170)
	at de.flapdoodle.embed.process.runtime.AbstractProcess$JobKiller.run(AbstractProcess.java:243)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by smecsia** [comment]
@kasheylm Which permissions do you have in the system? Postgres is known not to run with the root or admin privileges. 
Can you try to launch it manually? Somethins like this http://www.postgresql.org/docs/9.1/static/server-start.html

**Comment by smecsia** [comment]
Outdated.
