### ISSUE TITLE
The instance with different versions of the server does not work

### ISSUE THREAD

**Issue by BorzdeG** [yandex-qatools/postgresql-embedded#90]
TestD.groovy :

```
import ru.yandex.qatools.embed.postgresql.EmbeddedPostgres
import ru.yandex.qatools.embed.postgresql.distribution.Version

class TestD {
	static void main(String[] args) {
		def postgres = new EmbeddedPostgres(Version.Main.V9_6)
		postgres.start()
		println postgres.connectionUrl
		postgres.stop()

		def postgres1 = new EmbeddedPostgres(Version.Main.V9_5)
		postgres1.start()
		println postgres1.connectionUrl
		postgres1.stop()
	}
}
```

output:
```
Connected to the target VM, address: '127.0.0.1:61257', transport: 'socket'
:run TestD
Extract /Users/victor.alenkov/.embedpostgresql/postgresql-9.6.2-1-osx-binaries.zip START
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Extract /Users/victor.alenkov/.embedpostgresql/postgresql-9.6.2-1-osx-binaries.zip DONE
Optional[jdbc:postgresql://localhost:61271/postgres?user=postgres&password=postgres]

Optional[jdbc:postgresql://localhost:61279/postgres?user=postgres&password=postgres]

Disconnected from the target VM, address: '127.0.0.1:61257', transport: 'socket'
Could not delete pid file: /var/folders/w5/bxtb9q7n635fxz03k0c4_4240000gn/T/postgresql-embed-db74018f-34c8-43a7-a126-6d89a731141f/pgsql/bin/createdb.pid
Could not delete pid file: /var/folders/w5/bxtb9q7n635fxz03k0c4_4240000gn/T/postgresql-embed-db74018f-34c8-43a7-a126-6d89a731141f/pgsql/bin/initdb.pid
could not delete /var/folders/w5/bxtb9q7n635fxz03k0c4_4240000gn/T/postgresql-embed-db74018f-34c8-43a7-a126-6d89a731141f/pgsql/bin/pg_ctl.pid. Will try to delete it again when program exits.
Exception in thread "Thread-27" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at de.flapdoodle.embed.process.io.file.FileCleaner.forceDeleteOnExit(FileCleaner.java:52)
	at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:125)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:173)
	at de.flapdoodle.embed.process.runtime.AbstractProcess$JobKiller.run(AbstractProcess.java:243)
	at java.lang.Thread.run(Thread.java:748)

BUILD SUCCESSFUL in 12s
4 actionable tasks: 2 executed, 2 up-to-date
20:26:39: External task execution finished 'run TestD'.
```

**Comment by BorzdeG** [comment]
demo tests: https://github.com/BorzdeG/ru.itbasis.gradle.plugins.postgresql-embedded-plugin/blob/master/src/test/groovy/ru/itbasis/gradle/plugins/postgresql/PostgresqlEmbeddedPluginTest.groovy
